In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy 
from scipy import stats
import statsmodels.api as sm
from statsmodels.formula.api import ols
import datetime as dt
import datetime
from datetime import timedelta  
import timeboard as tb # turnos 

# para tratar de poner espanol
from datetime import date, datetime, time
from babel.dates import format_date, format_datetime, format_time, format_timedelta, Locale
import locale                                    # para tratar de poner espanol
#locale = Locale('es', 'CL')
locale.setlocale(locale.LC_ALL,'es_ES.UTF-8')  

import os
import runpy
from pyexcel_ods import get_data
from matplotlib_venn import venn3
from matplotlib_venn import venn2, venn2_circles
import math

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
%matplotlib inline


#otro graficador
import seaborn as sns

#stats

from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn import model_selection
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

/home/egidio/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools


# Importo fx locales

In [2]:
#listo los archivos
scripts = []
for dirname, dirnames, filenames in os.walk('/home/egidio/Dropbox/Compucosas/programas py'):
    for filename in filenames:
        scripts.append(os.path.join(dirname, filename))

scripts

# los cargo
for script in scripts:
    if script[-3:] == '.py':
        exec(open(str(script)).read())


['/home/egidio/Dropbox/Compucosas/programas py/lector_ODF.py',
 '/home/egidio/Dropbox/Compucosas/programas py/como importar',
 '/home/egidio/Dropbox/Compucosas/programas py/descripcion_univariada.py',
 '/home/egidio/Dropbox/Compucosas/programas py/características_operativas_de_test.py',
 '/home/egidio/Dropbox/Compucosas/programas py/percentiles.py',
 '/home/egidio/Dropbox/Compucosas/programas py/tabala_frecuencias.py',
 '/home/egidio/Dropbox/Compucosas/programas py/__pycache__/percentiles.cpython-36.pyc',
 '/home/egidio/Dropbox/Compucosas/programas py/__pycache__/lector_ODF.cpython-36.pyc',
 '/home/egidio/Dropbox/Compucosas/programas py/__pycache__/descripcion_univariada.cpython-36.pyc',
 '/home/egidio/Dropbox/Compucosas/programas py/__pycache__/características_operativas_de_test.cpython-36.pyc',
 '/home/egidio/Dropbox/Compucosas/programas py/__pycache__/tabala_frecuencias.cpython-36.pyc',
 '/home/egidio/Dropbox/Compucosas/programas py/__pycache__/funciones_locales.cpython-36.pyc']

# importo BD 

In [3]:
os.getcwd()

'/home/egidio/Dropbox/SAMU/Calidad registros eSAMU'

In [4]:
calidad = pd.read_excel('./Control calidad registros  Eversion1.xlsx')


In [5]:
calidad.head(3)

FECHA  N° REM Producto atención MLl. y SMLl atingentes  \
0  26/08/2019   97829              Otro                     Sí   
1  26/08/2019   97842        Trasladado                     No   
2  26/08/2019   97880   At en domicilio                     Sí   

  Teléfono registrado de llamante           ROp REM priorizado  \
0                              Sí  Hector Tapia             Sí   
1                              Sí     Luz Tapia             Sí   
2                              Sí     Luz Tapia             Sí   

  Regulación registrada En caso de cerrar REM queda claro motivos  \
0                    Sí                                       NaN   
1                    Sí                                       NaN   
2                    No                                       NaN   

  Campos de traslado: 4 enviantes, 4 receptores                   Regulador  \
0                                           NaN  Ulises Yañes, Orieta Bravo   
1                                           NaN               David Serrano   
2                                           NaN                Ulises Yañes   

  Paciente identificado Intervención Básica/Avanzada marcado  \
0                    Sí                                   Sí   
1                    Sí                                   Sí   
2                    Sí                                   Sí   

  Historia Clínica registrada Diagnóstico registrados  \
0                          Sí                      Sí   
1                          Sí                      Sí   
2                          Sí                      Sí   

  Prestación 1ria/2ria registrada CSV registrado  \
0                              No             Sí   
1                              Sí             Sí   
2                              Sí             Sí   

  Km inicial y final registrados Base intervención             Interventor  
0                             Sí          La Ligua   Enfermero Arturo Sire  
1                             Sí          La Ligua  TP Cristopher Martinez  
2                             Sí          La Ligua   Enfermero Arturo Sire

In [6]:
calidad.columns

Index(['FECHA', 'N° REM', 'Producto atención', 'MLl. y SMLl atingentes',
       'Teléfono registrado de llamante', 'ROp', 'REM priorizado',
       'Regulación registrada', 'En caso de cerrar REM queda claro motivos',
       'Campos de traslado: 4 enviantes, 4 receptores', 'Regulador',
       'Paciente identificado', 'Intervención Básica/Avanzada marcado',
       'Historia Clínica registrada', 'Diagnóstico registrados',
       'Prestación 1ria/2ria registrada', 'CSV registrado',
       'Km inicial y final registrados', 'Base intervención', 'Interventor'],
      dtype='object')

## Regulación ROp

Atingencia motivo y submotivo llamada

In [7]:
calidad['MLl. y SMLl atingentes'].value_counts()

Sí    59
No     8
Name: MLl. y SMLl atingentes, dtype: int64

In [149]:
file = open('Resultados.txt','w') 


<_io.TextIOWrapper name='testfile.txt' mode='w' encoding='UTF-8'>

In [8]:
calidad[calidad['MLl. y SMLl atingentes'] == 'No'].ROp.value_counts()

Maria Duran             3
Romyna Ramirez          2
Luz Tapia               1
Bastian Aliaga          1
Rosa del Carmen Meza    1
Name: ROp, dtype: int64

Registro telefónico

In [9]:
calidad['Teléfono registrado de llamante'].value_counts()

Sí    67
Name: Teléfono registrado de llamante, dtype: int64

In [146]:
# calidad[calidad['MLl. y SMLl atingentes'] == 'No'].ROp.value_counts()
# calidad[calidad['MLl. y SMLl atingentes'] == 'Si'].ROp.value_counts()
grupo = calidad.groupby(['MLl. y SMLl atingentes', 'ROp'])['N° REM'].count()

REMs = calidad.groupby(['MLl. y SMLl atingentes', 'ROp'])['N° REM'].apply(list)['No']

percbyrank = grupo.groupby(level=1).apply(lambda x: round(100 * x / float(x.sum())))
Mal_reg = {}
Mal_reg['n'] = grupo['No']
Mal_reg['%'] = percbyrank['No']
Mal_reg['REMs'] = REMs

Buen_reg = {}
Buen_reg['n'] = grupo['Sí']
Buen_reg['%'] = percbyrank['Sí']

ROP_MLL_peor = pd.DataFrame.from_dict(Mal_reg).sort_values(['%', 'n'])
ROP_MLL_mejor = pd.DataFrame.from_dict(Buen_reg).sort_values(['%', 'n'])

ROP_MLL_peor
ROP_MLL_mejor.head()

n      %                   REMs
ROp                                                  
Rosa del Carmen Meza  1   20.0               [100240]
Luz Tapia             1   33.0                [97842]
Romyna Ramirez        2   40.0        [98116, 100265]
Bastian Aliaga        1   50.0                [98318]
Maria Duran           3  100.0  [97821, 98047, 98001]

n      %
ROp                           
Bastian Aliaga        1   50.0
Romyna Ramirez        3   60.0
Luz Tapia             2   67.0
Rosa del Carmen Meza  4   80.0
Daniela Nuñez         1  100.0

Lo escribo en un texto que luego puede ser leído en latex

## Regulación regulador

### Si se priorizaron los REM para salida de ambulancia

Quiénes no lo hicieron?

Cuales fueron esos REM?

In [10]:
var = 'REM priorizado'
calidad[var].value_counts()
calidad[calidad[var] == 'No'].Regulador.value_counts()
calidad[calidad[var] == 'No']['N° REM'].values

Sí         50
No         12
<vacio>     1
Name: REM priorizado, dtype: int64

David Serrano                 2
Vincenzo Bavestrello          1
Ulises Yañez                  1
Juan Bulnes. Berta Garrido    1
Name: Regulador, dtype: int64

array([ 97821,  97875,  97916,  97995,  98195,  98093,  98287,  98301,
       100277, 100263, 100231, 100209])

### Se registró regulación?

Quiénes no lo hicieron?

Cuales fueron esos REM?


In [11]:
var = 'Regulación registrada'
calidad[var].value_counts()
calidad[calidad[var] == 'No'].Regulador.value_counts()
calidad[calidad[var] == 'No']['N° REM'].values

Sí         44
No         17
<vacio>     2
Name: Regulación registrada, dtype: int64

David Serrano         2
Ulises Yañes          1
Ulises Yañez          1
Estefania Martinez    1
Name: Regulador, dtype: int64

array([ 97880,  97913,  97917,  97836,  97821,  97875,  97916,  98009,
        98076,  97995,  98099,  98090,  98093,  98301, 100277, 100167,
       100297])

### En caso de cerrar REM queda claro motivos?

Quiénes no lo hicieron?

Cuales fueron esos REM?

In [12]:
var = 'En caso de cerrar REM queda claro motivos'
calidad[var].value_counts()
calidad[calidad[var] == 'No'].Regulador.value_counts()
calidad[calidad[var] == 'No']['N° REM'].values

Sí    23
No     4
Name: En caso de cerrar REM queda claro motivos, dtype: int64

David Serrano    2
Ulises Yañez     1
Name: Regulador, dtype: int64

array([ 97875,  98093, 100277, 100276])

### Campos de traslado: 4 enviantes, 4 receptores

Quiénes no lo hicieron?

Cuales fueron esos REM?

In [13]:
var = 'Campos de traslado: 4 enviantes, 4 receptores'
calidad[var].value_counts()
calidad[calidad[var] == 'No'].Regulador.value_counts()
calidad[calidad[var] == 'No']['N° REM'].values

Sí    6
No    6
Name: Campos de traslado: 4 enviantes, 4 receptores, dtype: int64

Ulises Yañez     3
Berta Garrido    1
Juan Veliz       1
Name: Regulador, dtype: int64

array([97835, 97836, 97881, 98042, 98080, 98254])

## Intervención

### Paciente identificado

Quiénes no lo hicieron?

Cuales fueron esos REM?

In [14]:
var = 'Paciente identificado'
SMUR = calidad[calidad[var] == 'No']['Base intervención'].dropna().unique()

calidad[var].value_counts()
calidad[calidad[var] == 'No']['Base intervención'].value_counts()
for base in SMUR:
    print('----------------------------')
    print(base, ':')
    calidad[calidad[var] == 'No'].groupby('Base intervención')['N° REM'].get_group(base).values
    calidad[calidad[var] == 'No'].groupby('Base intervención')['Interventor'].get_group(base).value_counts()

Sí    50
No     7
Name: Paciente identificado, dtype: int64

Viña del Mar    5
Quillota        1
Quintero        1
Name: Base intervención, dtype: int64

----------------------------
Viña del Mar :


array([ 97801,  97837,  97891,  98087, 100209])

TP Diego Fernandez                                     1
TP Sebastian Ahumada                                   1
Enfermero Victor Martínez/ Médico Sebastián Wiedman    1
TP Freddy San Martin                                   1
TP Daniel Flores                                       1
Name: Interventor, dtype: int64

----------------------------
Quintero :


array([98078])

Enfermera Daniela Torres    1
Name: Interventor, dtype: int64

----------------------------
Quillota :


array([98301])

Enfermero Jose Hidalgo    1
Name: Interventor, dtype: int64

### Intervención Básica/Avanzada marcado
Quiénes no lo hicieron?

Cuales fueron esos REM?

In [15]:
var = 'Intervención Básica/Avanzada marcado'
SMUR = calidad[calidad[var] == 'No']['Base intervención'].dropna().unique()

calidad[var].value_counts()
calidad[calidad[var] == 'No']['Base intervención'].value_counts()
for base in SMUR:
    print('----------------------------')
    print(base, ':')
    calidad[calidad[var] == 'No'].groupby('Base intervención')['N° REM'].get_group(base).values
    calidad[calidad[var] == 'No'].groupby('Base intervención')['Interventor'].get_group(base).value_counts()

Sí         45
No          6
<vacio>     2
Name: Intervención Básica/Avanzada marcado, dtype: int64

Viña del Mar    4
Quintero        2
Name: Base intervención, dtype: int64

----------------------------
Quintero :


array([97836, 97881])

Enfermera Francisca Lira    1
TP Javier Altamirano        1
Name: Interventor, dtype: int64

----------------------------
Viña del Mar :


array([97801, 97837, 97891, 98087])

TP Diego Fernandez      1
TP Sebastian Ahumada    1
TP Freddy San Martin    1
TP Daniel Flores        1
Name: Interventor, dtype: int64

### Historia Clínica registrada

Quiénes no lo hicieron?

Cuales fueron esos REM?

In [16]:
var = 'Historia Clínica registrada'
SMUR = calidad[calidad[var] == 'No']['Base intervención'].dropna().unique()

calidad[var].value_counts()
calidad[calidad[var] == 'No']['Base intervención'].value_counts()
for base in SMUR:
    print('----------------------------')
    print(base, ':')
    calidad[calidad[var] == 'No'].groupby('Base intervención')['N° REM'].get_group(base).values
    calidad[calidad[var] == 'No'].groupby('Base intervención')['Interventor'].get_group(base).value_counts()

Sí         41
No         11
<vacio>     1
Name: Historia Clínica registrada, dtype: int64

Viña del Mar    8
Quintero        3
Name: Base intervención, dtype: int64

----------------------------
Quintero :


array([97836, 97881, 98009])

TP Ruth Torres              1
Enfermera Francisca Lira    1
TP Javier Altamirano        1
Name: Interventor, dtype: int64

----------------------------
Viña del Mar :


array([ 97801,  97837,  97891,  98047,  98087,  98150, 100248, 100209])

TP Daniel Flores                                       2
TP Sebastian Ahumada                                   1
Enfermero Victor Martínez/ Médico Sebastián Wiedman    1
TP Marco Azocar                                        1
TP Diego Fernandez                                     1
TP Francisco Diaz                                      1
TP Freddy San Martin                                   1
Name: Interventor, dtype: int64

### Diagnóstico registrados
Quiénes no lo hicieron?

Cuales fueron esos REM?

In [17]:
var = 'Diagnóstico registrados'
SMUR = calidad[calidad[var] == 'No']['Base intervención'].dropna().unique()

calidad[var].value_counts()
calidad[calidad[var] == 'No']['Base intervención'].value_counts()
for base in SMUR:
    print('----------------------------')
    print(base, ':')
    calidad[calidad[var] == 'No'].groupby('Base intervención')['N° REM'].get_group(base).values
    calidad[calidad[var] == 'No'].groupby('Base intervención')['Interventor'].get_group(base).value_counts()

Sí         26
No         25
<vacio>     2
Name: Diagnóstico registrados, dtype: int64

Quillota        12
Viña del Mar     7
Quintero         6
Name: Base intervención, dtype: int64

----------------------------
Quillota :


array([ 97802,  97913,  97999,  98023,  98042,  98080,  98090,  98116,
        98254,  98318, 100308, 100240])

Enfermero Miguel Prieto        2
Enfermero Mauricio Escobar     2
Enfermero Eri Moreno           2
Enfermero Rodrigo Ortiz        1
Enfermera Cherie Caballero     1
Enfermero Guido Borquez        1
Enfermero Eleazar Navarrete    1
TP Verónica Laffi Marambio     1
Enfermero Daniel Callejas      1
Name: Interventor, dtype: int64

----------------------------
Quintero :


array([ 97836,  97881,  97948,  98009, 100212, 100167])

TP Ruth Torres              2
Enfermero Danko Andrade     2
TP Javier Altamirano        1
Enfermera Francisca Lira    1
Name: Interventor, dtype: int64

----------------------------
Viña del Mar :


array([ 97801,  97837,  97891,  98031,  98087, 100248, 100209])

TP Daniel Flores                                       2
TP Diego Fernandez                                     1
TP Sebastian Ahumada                                   1
Enfermero Victor Martínez/ Médico Sebastián Wiedman    1
TP Freddy San Martin                                   1
Enfermera Nicole Barrera                               1
Name: Interventor, dtype: int64

### Prestación 1ria/2ria registrada

Quiénes no lo hicieron?

Cuales fueron esos REM?

In [18]:
var = 'Prestación 1ria/2ria registrada'
SMUR = calidad[calidad[var] == 'No']['Base intervención'].dropna().unique()

calidad[var].value_counts()
calidad[calidad[var] == 'No']['Base intervención'].value_counts()
for base in SMUR:
    print('----------------------------')
    print(base, ':')
    calidad[calidad[var] == 'No'].groupby('Base intervención')['N° REM'].get_group(base).values
    calidad[calidad[var] == 'No'].groupby('Base intervención')['Interventor'].get_group(base).value_counts()

Sí         36
No         14
<vacio>     2
Name: Prestación 1ria/2ria registrada, dtype: int64

Viña del Mar    9
Quintero        2
Quillota        2
La Ligua        1
Name: Base intervención, dtype: int64

----------------------------
La Ligua :


array([97829])

Enfermero Arturo Sire    1
Name: Interventor, dtype: int64

----------------------------
Quintero :


array([97836, 97881])

Enfermera Francisca Lira    1
TP Javier Altamirano        1
Name: Interventor, dtype: int64

----------------------------
Viña del Mar :


array([ 97801,  97837,  97891,  97962,  98031,  98087,  98150, 100248,
       100209])

TP Daniel Flores                                       2
Enfermera Nicole Barrera                               2
TP Sebastian Ahumada                                   1
Enfermero Victor Martínez/ Médico Sebastián Wiedman    1
TP Diego Fernandez                                     1
TP Francisco Diaz                                      1
TP Freddy San Martin                                   1
Name: Interventor, dtype: int64

----------------------------
Quillota :


array([ 98080, 100240])

TP Verónica Laffi Marambio    1
Enfermera Cherie Caballero    1
Name: Interventor, dtype: int64

### CSV registrado

Quiénes no lo hicieron?

Cuales fueron esos REM?

In [19]:
var = 'CSV registrado'
SMUR = calidad[calidad[var] == 'No']['Base intervención'].dropna().unique()

calidad[var].value_counts()
calidad[calidad[var] == 'No']['Base intervención'].value_counts()
for base in SMUR:
    print('----------------------------')
    print(base, ':')
    calidad[calidad[var] == 'No'].groupby('Base intervención')['N° REM'].get_group(base).values
    calidad[calidad[var] == 'No'].groupby('Base intervención')['Interventor'].get_group(base).value_counts()

Sí         38
No         12
<vacio>     3
Name: CSV registrado, dtype: int64

Viña del Mar    7
Quintero        4
Quillota        1
Name: Base intervención, dtype: int64

----------------------------
Quintero :


array([ 97836,  97881,  98009, 100167])

TP Ruth Torres              2
Enfermera Francisca Lira    1
TP Javier Altamirano        1
Name: Interventor, dtype: int64

----------------------------
Viña del Mar :


array([ 97801,  97837,  97891,  98047,  98087, 100248, 100209])

TP Daniel Flores                                       2
TP Diego Fernandez                                     1
TP Marco Azocar                                        1
Enfermero Victor Martínez/ Médico Sebastián Wiedman    1
TP Freddy San Martin                                   1
TP Sebastian Ahumada                                   1
Name: Interventor, dtype: int64

----------------------------
Quillota :


array([98254])

Enfermero Eleazar Navarrete    1
Name: Interventor, dtype: int64

### Km inicial y final registrados

Quiénes no lo hicieron?

Cuales fueron esos REM?

In [20]:
var = 'Km inicial y final registrados'
SMUR = calidad[calidad[var] == 'No']['Base intervención'].dropna().unique()

calidad[var].value_counts()
calidad[calidad[var] == 'No']['Base intervención'].value_counts()
for base in SMUR:
    print('----------------------------')
    print(base, ':')
    calidad[calidad[var] == 'No'].groupby('Base intervención')['N° REM'].get_group(base).values
    calidad[calidad[var] == 'No'].groupby('Base intervención')['Interventor'].get_group(base).value_counts()

No    29
Sí    23
Name: Km inicial y final registrados, dtype: int64

Quintero            10
Quillota             9
Viña del Mar         9
Centro regulador     1
Name: Base intervención, dtype: int64

----------------------------
Quillota :


array([ 97913,  97917,  97999,  98042,  98080,  98254,  98318, 100308,
       100240])

Enfermero Miguel Prieto        2
Enfermero Eleazar Navarrete    2
Enfermero Mauricio Escobar     2
TP Verónica Laffi Marambio     1
Enfermera Cherie Caballero     1
Enfermero Daniel Callejas      1
Name: Interventor, dtype: int64

----------------------------
Quintero :


array([ 97835,  97836,  97881,  97948,  98009,  98078,  98185, 100212,
       100203, 100167])

Enfermero Danko Andrade     2
TP Ruth Torres              2
TP Juan Araya               1
TP Victoria Cuello          1
TP Juan Moreno              1
Enfermera Daniela Torres    1
TP Javier Altamirano        1
Enfermera Francisca Lira    1
Name: Interventor, dtype: int64

----------------------------
Viña del Mar :


array([ 97801,  97837,  97891,  98087,  98112,  98150, 100265, 100248,
       100209])

TP Daniel Flores                                       2
TP Sebastian Ahumada                                   1
Enfermero Victor Martínez/ Médico Sebastián Wiedman    1
Enfermero Erick Zúñiga                                 1
Enfermero Aldo Molina                                  1
TP Diego Fernandez                                     1
TP Francisco Diaz                                      1
TP Freddy San Martin                                   1
Name: Interventor, dtype: int64

----------------------------
Centro regulador :


array([98195])

TP David Rojo    1
Name: Interventor, dtype: int64